package com.tut.flowable.model;

public enum StatusEnum {
	
	DECLINEDBYCOMPANY,NOCANDIDATEFOUND,CLOSED,AWAITINGCONSENT,CONTACTED, NEW, INAPPLICATION,HIRED, MATCHED, CONSENTGIVEN,DENIEDBYCOMPANY,DECLINEDBYCANDIDATE,VALIDATE_CANDIDATE_PROFILE;

}
